services:
  - type: web
    name: finland-trade-dashboard
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:server
    plan: free

